language: python
python:
- '2.7'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
- pip install .
- pip install flake8 coverage nose mock
script:
- if [[ $TRAVIS_PYTHON_VERSION == "3.5" ]]; then nosetests --with-coverage --cover-package=descarteslabs
  --with-doctest --doctest-options=+ELLIPSIS,+NORMALIZE_WHITESPACE && flake8; fi
- if [[ $TRAVIS_PYTHON_VERSION != "3.5" ]]; then nosetests --with-coverage --cover-package=descarteslabs;
  fi
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: YZwfcAw1Sb5g/y3RyjhS89f71tqoYju7X5egU5nNZkdkpXXn0eQxwumIhfY+Z05S68VgOWXqEyb33U6RUNwRJq0YZAPfub+IZVIUu6zjdaf5Z+4UvZqAKjLZWTFm9oDevZjmyZ+OGgcgO4XqUZX2xyVRtF3x7qAG2MseXUqAMNz/S89DuMayrbKcHNVAwbxZOU1WcjP9tUHQvxPAZYyIEtZl7NObz4SWIYzN4Z5zkNtpqC/ttzhopmhLH7kytVxP/vrMrI1XrPX45LysVv52ign846LM95vLkYuLCP2tHzMnVPV3TD3AjRv5ngvwiO/0NGfeOZqXoVJFov6BmCEDGzZvnM1YeGJdDyfXUdtpFLrvowsRh1h6omALG1M6WUTl3GhASfWfj5jTYia49IY6/Vl+uLqQSUL5DTm+uU2hZnTrTLSgf4sxmNUreqoRCnKyZmPdYHeuyyRfqQQphO7tl1hMXW71XuDcyp7mfjjOx20xRvMGL8ciNWK/MZ6depL3KFdh+Ot964AoOeIbnADnFx8Y55929pmnTnuRFw+6HTgfSHxS7Zr4a/+VtgKm0eBKvMZyubZb832GoLRDrrn+FAnUABo5zEqngTiFA0Oq/Xq//f7loEMoahEznqluPyX18/W7DbWRFWHCqxyLeIm/CNhyO8rY4EHGmsC/x2E8JD8=
